### ISSUE TITLE
Problem with URI: Expected a value of type 'Iterable<dynamic>', but got one of type 'DateTime'

### ISSUE THREAD

**Issue by dhilipkumars** [aeyrium/sunrise-sunset#1]
Hi 
When i make a simple call like below but supply `date` then i get below error.
```
var response = await SunriseSunset.getResults(
     date: DateTime.now().toLocal(),
      latitude: locationLat,
      longitude: locationLong,
    );
```

response
```
Problem with URI: Expected a value of type 'Iterable<dynamic>', but got one of type 'DateTime'
```

**Comment by diegoveloper** [comment]
@dhilipkumars I fixed the issue, run `flutter pub upgrade`

**Comment by diegoveloper** [comment]
@dhilipkumars we released a new version, did you try?

**Comment by dhilipkumars** [comment]
Thanks for the quick fix and thanks for the package, will try soon , Also directly doing `Datetime.toString()` works to instead of just stripping just the `date` part  it.

**Comment by dhilipkumars** [comment]
works fine thanks for the help.
